# String Methods

In [9]:
string1 = "Today is Friday and Monday"

In [10]:
len() -> length

SyntaxError: invalid syntax (Temp/ipykernel_16468/1664451069.py, line 1)

In [ ]:
SYNTAX: name_of_the_function(data or variable)

In [ ]:
string1

'Today is Friday and Monday'

In [11]:
len(string1)

26

In [ ]:
# Checking the value in a string

"is" in string1

True

In [ ]:
"this" in string1

False

In [ ]:
# Checking the value in a string

In [ ]:
veggies = ["Potatoes", "Peas", "Tomatoes", "Beans", "Apple"]

In [ ]:
var = value
var1
var2
.....var(n)

In [ ]:
veggies

['Potatoes', 'Peas', 'Tomatoes', 'Beans', 'Apple']

In [ ]:
type(veggies)

list

In [ ]:
veggies[2]

'Tomatoes'

In [ ]:
veggies[-3]

'Tomatoes'

In [ ]:
veggies.append('Kiwi')

In [ ]:
veggies

['Potatoes', 'Peas', 'Tomatoes', 'Beans', 'Apple', 'Kiwi']

In [ ]:
veggies[1] = "Pizza"

In [ ]:
veggies

['Potatoes', 'Pizza', 'Tomatoes', 'Beans', 'Apple', 'Kiwi']

In [ ]:
tup = ('Potatoes', 'Pizza', 'Tomatoes', 'Beans', 'Apple', 'Kiwi')

In [ ]:
tup

('Potatoes', 'Pizza', 'Tomatoes', 'Beans', 'Apple', 'Kiwi')

In [ ]:
type(tup)

tuple

In [ ]:
tup[1] = "Peas"

TypeError: ignored

In [ ]:
tup

('Potatoes', 'Pizza', 'Tomatoes', 'Beans', 'Apple', 'Kiwi')

In [ ]:
list1 = list(tup)

In [ ]:
list1

['Potatoes', 'Pizza', 'Tomatoes', 'Beans', 'Apple', 'Kiwi']

In [ ]:
list1[1]="Peas"

In [ ]:
list1

['Potatoes', 'Peas', 'Tomatoes', 'Beans', 'Apple', 'Kiwi']

In [ ]:
tup = tuple(list1)

In [ ]:
tup

('Potatoes', 'Peas', 'Tomatoes', 'Beans', 'Apple', 'Kiwi')

In [ ]:
set1 = {1,2,1,1,2,3}

In [ ]:
set1

{1, 2, 3}

In [ ]:
dictionary = {"Pencil":23, "Car":45}

In [ ]:
type(dictionary)

dict

In [ ]:
dictionary

{'Car': 45, 'Pencil': 23}

In [ ]:
dictionary['Car']

45

In [ ]:
dictionary.keys()

dict_keys(['Pencil', 'Car'])

In [ ]:
dictionary.values()

dict_values([23, 45])

In [ ]:
amount = 350

In [ ]:
if amount >= 501 and amount <= 1000:
  print('RC Car')
elif amount >= 101 and amount <= 500:
  print('Beyblade')
elif amount >= 10 and amount <=100:
  print('Trump Cards')
else:
  print('Cry')

Beyblade


In [5]:
attendence = True
project = True

In [6]:
if attendence:
  if project:
    print('You will be getting the certificate')
  else:
    print('You will not be getting the certificate')
else:
  print('You will not be getting the certificate')

You will be getting the certificate


In [ ]:
# For Loop

for i in range(10):
  print("Hello World", i)

Hello World 0
Hello World 1
Hello World 2
Hello World 3
Hello World 4
Hello World 5
Hello World 6
Hello World 7
Hello World 8
Hello World 9


In [ ]:
10k - 30k

In [ ]:
0 (Inclusive) - 10 (Exclusive)

0
1
2
3
4
5
6
7
8
9

In [ ]:
count = 0
while count < 10:
  print('Hello World')

Streaming output truncated to the last 5000 lines.
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
H

KeyboardInterrupt: ignored

In [ ]:
count = 0
while count < 10:
  print('Hello World', count)
  # count = count + 1
  count += 5

Hello World 0
Hello World 5


In [ ]:
count

10

In [ ]:
10 < 10

False

In [ ]:
count

10

In [ ]:
pip install pandas

# Importing the libraries

In [7]:
import numpy as np
import pandas as pd # Data Manipulation, Data Cleaning, Data Exploration, Data Visualization
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split

# Import the dataset

In [8]:
df = pd.read_csv("/content/drive/MyDrive/Python and Machine Learning - 2022/IceCreamData.csv")

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/Python and Machine Learning - 2022/IceCreamData.csv'

In [ ]:
df

Temperature     Revenue
0      24.566884  534.799028
1      26.005191  625.190122
2      27.790554  660.632289
3      20.595335  487.706960
4      11.503498  316.240194
..           ...         ...
495    22.274899  524.746364
496    32.893092  755.818399
497    12.588157  306.090719
498    22.362402  566.217304
499    28.957736  655.660388

[500 rows x 2 columns]

In [ ]:
df.head(10)

Temperature     Revenue
0    24.566884  534.799028
1    26.005191  625.190122
2    27.790554  660.632289
3    20.595335  487.706960
4    11.503498  316.240194
5    14.352514  367.940744
6    13.707780  308.894518
7    30.833985  696.716640
8     0.976870   55.390338
9    31.669465  737.800824

In [ ]:
df.tail(15)

Temperature     Revenue
485    23.407257  501.345330
486    12.301615  333.334258
487    32.632858  793.079011
488    16.703852  379.318226
489    26.964217  581.074005
490    23.824922  584.399945
491    34.472169  809.352519
492    23.056214  552.819351
493    14.931506  377.430928
494    25.112066  571.434257
495    22.274899  524.746364
496    32.893092  755.818399
497    12.588157  306.090719
498    22.362402  566.217304
499    28.957736  655.660388

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Temperature  500 non-null    float64
 1   Revenue      500 non-null    float64
dtypes: float64(2)
memory usage: 7.9 KB


In [ ]:
Age -> int

In [ ]:
"45"

In [ ]:
Name -> x
Age -> x
Email ->

In [ ]:
500 - 499 = 1

In [ ]:
df.shape

(500, 2)

In [ ]:
df.describe()

Temperature      Revenue
count   500.000000   500.000000
mean     22.232225   521.570777
std       8.096388   175.404751
min       0.000000    10.000000
25%      17.122258   405.558681
50%      22.392791   529.368565
75%      27.740674   642.257922
max      45.000000  1000.000000

In [ ]:
df.columns

Index(['Temperature', 'Revenue'], dtype='object')

In [ ]:
df['Temperature']

0      24.566884
1      26.005191
2      27.790554
3      20.595335
4      11.503498
         ...    
495    22.274899
496    32.893092
497    12.588157
498    22.362402
499    28.957736
Name: Temperature, Length: 500, dtype: float64

In [ ]:
X = df.Temperature
y = df.Revenue

In [ ]:
df.ndim

2

In [ ]:
X.ndim

1

In [ ]:
y.ndim

1

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

In [ ]:
len(X_train)

400

In [ ]:
len(X_test)

100

In [ ]:
model = LinearRegression()

In [ ]:
model.fit(np.array([X_train]).reshape(-1,1), y_train)

LinearRegression()

In [ ]:
y_pred = model.predict(np.array([X_test]).reshape(-1,1))

In [ ]:
y_pred

array([233.9569213 , 509.27373948, 495.31091916, 447.21463562,
       160.11750763, 681.02888224, 678.27187457, 675.58625537,
       450.99993572, 412.11923116, 658.18143268, 561.27277147,
       386.13535996, 650.11722874, 609.47824082, 662.58287067,
       449.45804716, 402.95431604, 803.37266825, 440.97105237,
       526.42872769, 392.00295299, 291.84225118, 724.17595911,
       443.00038092, 207.6085325 , 707.6634145 , 626.97229111,
       638.48618008, 421.5511321 , 368.74844816, 311.70521217,
       669.63059601, 709.05748279, 497.82463256, 653.63842832,
       522.75972431, 285.09605405, 282.34706576, 732.06352997,
       807.31215063, 427.89614863, 609.28111153, 620.24339893,
       629.83121559, 830.2519635 , 680.78333319, 581.41439792,
       338.93949547, 756.17731677, 534.10289074, 561.01679397,
       482.1628358 , 634.52405974, 457.73596102, 255.71219742,
       657.85112862, 570.95783234, 525.68594371, 589.24868242,
       659.29428417, 588.34040615, 352.71504297, 211.54

In [ ]:
y_test 

439    264.123914
419    505.743867
429    521.775445
42     421.621505
267    145.625302
          ...    
401    916.648613
243    367.052376
333    508.720471
130    496.011917
50     190.710941
Name: Revenue, Length: 100, dtype: float64

In [ ]:
r2_score(y_test, y_pred)

0.9820935737686565

In [ ]:
model.predict([[17]])

array([409.28189194])

* Day 7 Attendence: https://forms.gle/C8G3DKPfLhb76urD8

* Jamboard: https://jamboard.google.com/d/1JqQuN2_ihATnKxaZRO9RtEZSgNw6fHizYeMtAGHlDkw/edit?usp=sharing, https://jamboard.google.com/d/1kHQiwrz6fHE7Fbq4pC1DxdQejcUryJZxH71QAVrGL3o/edit?usp=sharing

* Dataset: https://drive.google.com/file/d/1mGd1jwG1jExXmJpmGgDhUY9awevlopdD/view?usp=sharing


* Project Submission: https://forms.gle/FZKX9pdR53XHDjHy8

**PROJECT IMPLEMENTATION**
                          :- KARTIK NAMBIAR

In [1]:
import numpy as np
import pandas as pd # Data Manipulation, Data Cleaning, Data Exploration, Data Visualization
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import StandardScaler

READ CSV FILE

In [2]:
df = pd.read_csv(r"C:\Users\nambi\Housing (1).csv")

Shows us no null values are present

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   price             545 non-null    int64 
 1   area              545 non-null    int64 
 2   bedrooms          545 non-null    int64 
 3   bathrooms         545 non-null    int64 
 4   stories           545 non-null    int64 
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64 
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB


Changing String Values into Binary values

In [4]:
df.mainroad.replace(to_replace=['yes','no'],value=[1,0], inplace=True)
df.guestroom.replace(to_replace=['yes', 'no'], value=[1,0], inplace=True)
df.basement.replace(to_replace=['yes','no'],value=[1,0], inplace=True)
df.hotwaterheating.replace(to_replace=['yes', 'no'], value=[1,0], inplace=True)
df.airconditioning.replace(to_replace=['yes','no'],value=[1,0], inplace=True)
df.parking.replace(to_replace=['yes', 'no'], value=[1,0], inplace=True)
df.prefarea.replace(to_replace=['yes','no'],value=[1,0], inplace=True)
df.furnishingstatus.replace(to_replace=['furnished', 'semi-furnished','unfurnished'], value=[1,0.5,0], inplace=True)

In [5]:
f_var_list = ['area', 'bedrooms', 'bathrooms', 'stories', 'mainroad',
              'guestroom', 'basement', 'hotwaterheating', 'airconditioning',
              'parking', 'prefarea','furnishingstatus']
x = df[f_var_list]

y = df['price']



In [6]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

Linear regression model 

In [7]:
y_train_reshaped = y_train.values.reshape(-1,1)
y_test_reshaped = y_test.values.reshape(-1,1)

model = LinearRegression()
model.fit(x_train, y_train_reshaped)

slope = model.coef_

print('The names of the features along with the values of their corresponding coefficients :-')
for i in range(len(f_var_list)):
  print(f_var_list[i], slope[0][i], sep='\n')

The names of the features along with the values of their corresponding coefficients :-
area
235.8487717881368
bedrooms
78574.49238760094
bathrooms
1097117.266147957
stories
406223.1644628834
mainroad
366824.1923924822
guestroom
233146.76562654975
basement
393159.7787258417
hotwaterheating
687881.3109570172
airconditioning
785550.5792954292
parking
225756.51397628197
prefarea
629901.6608459125
furnishingstatus
420794.2365431118


In [8]:
y_train_pred = model.predict(x_train)
y_test_pred = model.predict(x_test)

ACCURACY

In [9]:
print("For Train set:-")
print(f"R-squared: {r2_score(y_train_reshaped, y_train_pred)}")
print("For Test set:-")      
print(f"R-squared: {r2_score(y_test_reshaped, y_test_pred):}")


For Train set:-
R-squared: 0.6854429472843789
For Test set:-
R-squared: 0.6494754192267804


PREDICTION

In [10]:
model.predict([[7000,4,2,3,1,0,0,0,1,2,1,0]])


array([[7484221.69084588]])

Predicted price:-7484221.69084588

In [11]:
import pickle
with open('model.pkl','wb') as files:
    pickle.dump(model,files)